// Isolated UI verification. All records are synthetic and stay in memory.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
const loader = require('../server/sheetsLoader');
loader.loadQuestions = async () => ({ sets: {}, setNames: [], totalCount: 0, lastFetched: new Date().toISOString() });
const { server, auth, io } = require('../server/index');
const { hashPassword } = require('../server/auth');
const tables = { AccountsV2: [], QuizAccessV2: [], MediaUploadsV2: [], AppSettingsV2: [] };
auth.store.all = async table => structuredClone(tables[table]);
auth.store.save = async (table, value) => {
  if (value._row) tables[table][value._row - 2] = structuredClone(value);
  else tables[table].push({ ...value, _row: tables[table].length + 2 });
};
(async () => {
  const password = 'Aa1!';
  const password_hash = await hashPassword(password);
  await auth.store.save('AccountsV2', { id: 'admin', username: 'demo.admin', name: 'Admin Demo', password_hash, role: 'super_admin', status: 'active', version: '1', must_change_password: 'false', created_at: new Date().toISOString() });
  for (let n = 1; n <= 4; n++) await auth.store.save('AccountsV2', { id: `collab${n}`, username: `rekan${n}`, name: `Rekan ${n}`, password_hash, role: 'creator', status: 'active', version: '1', must_change_password: 'false', created_at: new Date().toISOString() });
  for (const [id, name] of [['trainer', 'Rina Pratiwi'], ['trainer2', 'Muhammad Akhsanul Sadikin']]) await auth.store.save('AccountsV2', { id, username: `demo.${id}`, name, password_hash, role: 'creator', status: 'pending', version: '1', must_change_password: 'false', created_at: new Date().toISOString() });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  const browser = await chromium.launch({ headless: true });
  const folder = path.resolve('.impeccable/review'); fs.mkdirSync(folder, { recursive: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1365, height: 900 } });
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    await page.goto(base + '/auth/');
    await page.getByRole('button', { name: 'Masuk', exact: true }).waitFor();
    assert.equal(await page.getByRole('link', { name: 'Gabung kuis', exact: true }).getAttribute('href'), '/player');
    await page.getByLabel('Password', { exact: true }).fill('Visibility1!');
    await page.getByRole('button', { name: 'Tampilkan password', exact: true }).click();
    assert.equal(await page.getByLabel('Password', { exact: true }).getAttribute('type'), 'text');
    await page.getByRole('button', { name: 'Sembunyikan password', exact: true }).press('Enter');
    assert.equal(await page.getByLabel('Password', { exact: true }).getAttribute('type'), 'password');
    await page.getByLabel('Password', { exact: true }).fill('');
    await page.screenshot({ path: path.join(folder, 'desktop.png'), fullPage: true });
    await page.setViewportSize({ width: 1280, height: 720 });
    await page.getByText('Kontak belum diatur. Hubungi fasilitator atau pengelola Nizhoot di kantor Anda.').waitFor();
    await page.screenshot({ path: path.join(folder, 'desktop-short.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: path.join(folder, 'mobile.png'), fullPage: true });
    await page.getByRole('button', { name: 'Belum punya akun? Daftar' }).click();
    assert.equal(await page.evaluate(() => document.activeElement.id), 'form-title', JSON.stringify(errors));
    await page.getByLabel('Nama lengkap', { exact: true }).fill('Nama tersimpan');
    await page.getByLabel('Username', { exact: true }).fill('draft.user');
    await page.getByRole('button', { name: 'Sudah punya akun? Masuk' }).click();
    await page.getByRole('button', { name: 'Belum punya akun? Daftar' }).click();
    assert.equal(await page.getByLabel('Nama lengkap', { exact: true }).inputValue(), 'Nama tersimpan');
    assert.equal(await page.getByLabel('Username', { exact: true }).inputValue(), 'draft.user');
    await page.getByLabel('Username', { exact: true }).fill('invalid username');
    await page.getByRole('button', { name: 'Kirim pendaftaran' }).click();
    assert.equal(await page.evaluate(() => document.activeElement.id), 'username');
    assert.equal(await page.getByLabel('Username', { exact: true }).getAttribute('aria-invalid'), 'true');
    await page.getByLabel('Nama lengkap', { exact: true }).fill('Peserta Uji Browser');
    await page.getByLabel('Username', { exact: true }).fill('demo.browser');
    await page.getByLabel('Password', { exact: true }).fill(password);
    await page.getByLabel('Ulangi password', { exact: true }).fill('Mismatch1!');
    await page.getByRole('button', { name: 'Kirim pendaftaran' }).click();
    assert.equal(await page.evaluate(() => document.activeElement.id), 'confirm');
    assert.equal(await page.getByLabel('Ulangi password', { exact: true }).getAttribute('aria-invalid'), 'true');
    await page.getByLabel('Ulangi password', { exact: true }).fill(password);
    await page.getByLabel('Password', { exact: true }).fill('Aa12');
    await page.getByRole('button', { name: 'Kirim pendaftaran' }).click();
    await page.getByText('Gunakan huruf besar, huruf kecil, angka, dan simbol (maksimal 128 karakter).', { exact: true }).waitFor();
    await page.getByLabel('Password', { exact: true }).fill(password);
    await page.getByRole('button', { name: 'Kirim pendaftaran' }).click();
    await page.getByRole('heading', { name: 'Pendaftaran sedang ditinjau' }).waitFor();
    await page.screenshot({ path: path.join(folder, 'mobile-pending.png'), fullPage: true });
    await page.getByRole('button', { name: 'Periksa status' }).click();
    await page.getByText('Masih menunggu persetujuan super admin.').waitFor();
    await page.getByRole('button', { name: 'Keluar', exact: true }).click();
    await page.getByLabel('Username', { exact: true }).fill('demo.admin');
    await page.getByLabel('Password', { exact: true }).fill(password);
    await page.getByRole('button', { name: 'Masuk', exact: true }).click();
    await page.waitForURL('**/admin/');
    await page.locator('#btnOpenCreateSetModal').click();
    await page.locator('#inputModalSetName').fill('Kuis Kolaborasi');
    await page.locator('#collaborator-search').fill('Rekan');
    for (let n = 1; n <= 4; n++) await page.getByRole('button', { name: `Rekan ${n} · @rekan${n}`, exact: true }).click();
    await page.screenshot({ path: path.join(folder, 'quiz-create-collaborators-mobile.png'), fullPage: true });
    await page.getByRole('button', { name: 'Buat kuis', exact: true }).click();
    await page.locator('#btnManageCollaborators').waitFor();
    await page.locator('#btnBackToDashboard').click();
    await page.getByText('Pemilik: Anda', { exact: true }).waitFor();
    await page.getByText('+1 lainnya', { exact: true }).click();
    await page.screenshot({ path: path.join(folder, 'quiz-collaborators-mobile.png'), fullPage: true });
    await page.getByRole('heading', { name: 'Kuis Kolaborasi', exact: true }).click();
    await page.locator('#btnManageCollaborators').click();
    await page.getByRole('button', { name: 'Hapus kolaborator Rekan 4', exact: true }).click();
    await page.getByRole('button', { name: 'Simpan kolaborator', exact: true }).click();
    await page.locator('#btnManageCollaborators').waitFor();
    assert.equal(tables.QuizAccessV2.find(r => r.quiz_set === 'Kuis Kolaborasi').collaborators.split(',').length, 3);
    const collaborator = await browser.newPage({ viewport: { width: 1280, height: 720 } });
    await collaborator.goto(base + '/auth/');
    await collaborator.getByLabel('Username', { exact: true }).fill('rekan1');
    await collaborator.getByLabel('Password', { exact: true }).fill(password);
    await collaborator.getByRole('button', { name: 'Masuk', exact: true }).click();
    await collaborator.waitForURL('**/admin/');
    await collaborator.getByText('Pemilik: Admin Demo (@demo.admin)', { exact: true }).waitFor();
    assert.equal(await collaborator.locator('.quiz-card-btn-delete').isVisible(), false);
    await collaborator.screenshot({ path: path.join(folder, 'quiz-collaborator-desktop.png'), fullPage: true });
    await collaborator.close();
    await page.goto(base + '/auth/?view=settings');
    await page.locator('#photo').setInputFiles(path.resolve('public/assets/images/nizhoot-logo.png'));
    await page.getByText('Foto siap. Pilih Simpan profil untuk menyimpan perubahan.', { exact: true }).waitFor();
    await page.getByLabel('Nama lengkap', { exact: true }).fill('Admin Profil');
    await page.getByRole('button', { name: 'Simpan profil', exact: true }).click();
    await page.getByText('Profil berhasil disimpan.', { exact: true }).waitFor();
    await page.getByLabel('Nama lengkap', { exact: true }).fill('Admin Demo');
    await page.getByRole('button', { name: 'Simpan profil', exact: true }).click();
    await page.getByText('Profil berhasil disimpan.', { exact: true }).waitFor();
    await page.locator('#username-tab').click();
    await page.getByLabel('Username', { exact: true }).fill('demo.admin.new');
    await page.getByLabel('Password saat ini', { exact: true }).fill(password);
    await page.getByRole('button', { name: 'Simpan username', exact: true }).click();
    await page.getByText('Username berhasil diubah menjadi @demo.admin.new. Gunakan username ini saat login.', { exact: true }).waitFor();
    await page.reload();
    await page.getByLabel('Nama lengkap', { exact: true }).waitFor();
    assert.equal(await page.getByLabel('Nama lengkap', { exact: true }).inputValue(), 'Admin Demo');
    assert.match(await page.locator('#photo-preview img').getAttribute('src'), /^data:image\/webp;base64,/);
    await page.screenshot({ path: path.join(folder, 'settings-mobile.png'), fullPage: true });
    assert.equal(await page.locator('#remove-photo').evaluate(node => node.getBoundingClientRect().top >= document.getElementById('photo-help').getBoundingClientRect().bottom + 15), true);
    await page.locator('#security-tab').click();
    assert.equal(await page.locator('#security-tab').getAttribute('aria-current'), 'page');
    await page.getByLabel('Password saat ini', { exact: true }).fill(password);
    await page.getByLabel('Password baru', { exact: true }).fill('Dd4!');
    await page.getByLabel('Ulangi password baru', { exact: true }).fill('Dd4!');
    await page.getByRole('button', { name: 'Simpan password', exact: true }).click();
    await page.getByText('Password berhasil diperbarui. Gunakan password baru saat login berikutnya.', { exact: true }).waitFor();
    assert.equal(await page.getByLabel('Password baru', { exact: true }).inputValue(), '');
    await page.screenshot({ path: path.join(folder, 'settings-security-mobile.png'), fullPage: true });
    await page.goto(base + '/admin/');
    await page.getByRole('button', { name: 'Menu akun Admin Demo' }).click();
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('.profile-trigger').getAttribute('aria-expanded'), 'false');
    await page.locator('.profile-trigger').click();
    await page.setViewportSize({ width: 1280, height: 720 });
    await page.screenshot({ path: path.join(folder, 'profile-desktop.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: path.join(folder, 'profile-mobile.png'), fullPage: true });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.getByRole('link', { name: 'Kelola pengguna' }).click();
    await page.getByRole('heading', { name: 'Rina Pratiwi' }).waitFor();
    await page.route('**/api/accounts', route => route.fulfill({ status: 503, json: { error: 'Daftar uji tidak tersedia.' } }));
    await page.getByRole('button', { name: 'Muat ulang', exact: true }).click();
    await page.locator('#load-error').waitFor({ state: 'visible' });
    await page.unroute('**/api/accounts');
    await page.getByRole('button', { name: 'Muat ulang', exact: true }).click();
    await page.locator('#load-error').waitFor({ state: 'hidden' });
    await page.getByRole('heading', { name: 'Rina Pratiwi' }).waitFor();
    await page.getByText('Kontak bantuan akun', { exact: true }).click();
    await page.getByLabel('Nama kontak', { exact: true }).fill('Tim Bantuan Demo');
    await page.getByLabel('Alamat kontak', { exact: true }).fill('help@example.test');
    await page.getByRole('button', { name: 'Simpan kontak', exact: true }).click();
    await page.getByText('Kontak bantuan disimpan dan tampil di halaman akun.').waitFor();
    const helpPage = await browser.newPage();
    await helpPage.goto(base + '/auth/');
    assert.equal(await helpPage.getByRole('link', { name: 'Hubungi Tim Bantuan Demo' }).getAttribute('href'), 'mailto:help@example.test');
    await helpPage.close();
    await page.getByText('Kontak bantuan akun', { exact: true }).click();
    await page.screenshot({ path: path.join(folder, 'mobile-accounts.png'), fullPage: true });
    await page.setViewportSize({ width: 1365, height: 900 });
    await page.screenshot({ path: path.join(folder, 'desktop-accounts.png'), fullPage: true });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.getByRole('button', { name: 'Setujui Rina Pratiwi', exact: true }).click();
    let releaseApproval;
    const approvalStarted = new Promise(resolve => {
      page.route('**/api/accounts/trainer/approve', async route => {
        await new Promise(release => { releaseApproval = release; resolve(); });
        await route.continue();
      });
    });
    await page.getByRole('dialog').getByRole('button', { name: 'Setujui', exact: true }).click();
    await approvalStarted;
    assert.equal(await page.locator('#cancel').isDisabled(), true);
    assert.equal(await page.locator('#confirm').textContent(), 'Memproses…');
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('dialog').evaluate(node => node.open), true);
    releaseApproval();
    await page.getByText('Setujui berhasil untuk Rina Pratiwi.').waitFor();
    await page.locator('#load-error').waitFor({ state: 'hidden' });
    assert.equal(await page.locator('#message').textContent(), 'Setujui berhasil untuk Rina Pratiwi.');
    await page.getByLabel('Status akun').selectOption('active');
    await page.getByRole('button', { name: 'Reset password Rina Pratiwi', exact: true }).click();
    await page.getByLabel('Password sementara', { exact: true }).fill('Bb2@');
    await page.getByRole('dialog').getByRole('button', { name: 'Reset password', exact: true }).click();
    await page.getByText('Reset password berhasil untuk Rina Pratiwi.').waitFor();
    await page.locator('.profile-trigger').click();
    await page.getByRole('button', { name: 'Keluar', exact: true }).click();
    await page.waitForURL('**/auth/');
    await page.getByLabel('Username', { exact: true }).fill('demo.trainer');
    await page.getByLabel('Password', { exact: true }).fill('Bb2@');
    await page.getByRole('button', { name: 'Masuk', exact: true }).click();
    await page.getByRole('heading', { name: 'Buat password baru' }).waitFor();
    assert.match(await page.locator('.password-identity').textContent(), /Rina Pratiwi.*@demo.trainer/);
    assert.equal(await page.locator('.steps').isVisible(), false);
    await page.screenshot({ path: path.join(folder, 'password-identity.png'), fullPage: true });
    await page.getByLabel('Password saat ini', { exact: true }).fill('Bb2@');
    await page.getByLabel('Password baru', { exact: true }).fill('Cc3#');
    await page.getByLabel('Ulangi password baru', { exact: true }).fill('Cc3#');
    await page.getByRole('button', { name: 'Simpan password' }).click();
    await page.waitForURL('**/admin/');
    // A player socket may connect without an account but cannot perform host actions.
    const anonymous = await browser.newPage(); await anonymous.goto(base + '/player');
    const denied = await anonymous.evaluate(() => new Promise((resolve, reject) => {
      const socket = io(); const timer = setTimeout(() => reject(new Error('No host denial')), 4000);
      socket.on('connect', () => socket.emit('host:create_room', { quizSet: 'Private' }));
      socket.on('host:error', result => { clearTimeout(timer); socket.disconnect(); resolve(result.message); });
    }));
    assert.match(denied, /ditolak/);
    assert.deepEqual(errors, []);
    console.log('Browser checks passed: registration, pending refresh, approval, reset, forced password change, anonymous socket denial; desktop/mobile captures saved.');
  } finally { await browser.close(); io.close(); server.close(); }
})().catch(error => { console.error(error); io.close(); server.close(); process.exitCode = 1; });




